config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls', 'main')),
    path("mailing/", include('mailing_service.urls', 'mailing')),
    path("users/", include('users.urls', 'users')),
    path("blogs/", include('blogs.urls', 'blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_service/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_service.views import dashboard, ClientListView, MailingListView, MailingCreateView, MailingUpdateView, \
    MessageCreateView, MessageListView, ClientCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    MailingDetailView, MailingDeleteView, ClientDetailView, ClientUpdateView, ClientDeleteView, MailingLogListView, \
    toggle_mailing, moderator_dashboard
from mailing_service.apps import MailingServiceConfig


app_name = MailingServiceConfig.name


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),  # кеширование убрала потому что можно снова попасть в ЛК
    path('moderator_dashboard/', moderator_dashboard, name='moderator_dashboard'),

    path('client_list/', cache_page(5)(ClientListView.as_view()), name='client_list'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('view_client/<int:pk>', ClientDetailView.as_view(), name='view_client'),
    path('update_client/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),

    path('mailing_list/', cache_page(5)(MailingListView.as_view()), name='mailing_list'),
    path('create_mail/', MailingCreateView.as_view(), name='create_mail'),
    path('view_mail/<int:pk>', MailingDetailView.as_view(), name='view_mail'),
    path('update_mail/<int:pk>/', MailingUpdateView.as_view(), name='update_mail'),
    path('delete_mail/<int:pk>/', MailingDeleteView.as_view(), name='delete_mail'),

    path('message_list/', cache_page(5)(MessageListView.as_view()), name='message_list'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('view_message/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('log_list/', cache_page(5)(MailingLogListView.as_view()), name='log_list'),
    path('toggle_mailing/<int:pk>', toggle_mailing, name='toggle_mailing'),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import index, contacts, noway_page, access_denied

app_name = MainConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('noway/', noway_page, name='noway'),
    path('access_denied/', access_denied, name='access_denied'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    """ Пользователь """

    username = None

    email = models.EmailField(unique=True, verbose_name="Email")
    first_name = models.CharField(max_length=100, verbose_name="Имя")
    last_name = models.CharField(max_length=100, verbose_name="Фамилия")
    middle_name = models.CharField(max_length=100, verbose_name="Отчество", default="", **NULLABLE)
    phone_number = PhoneNumberField(verbose_name="Номер телефона", default="+7", **NULLABLE)
    avatar = models.ImageField(upload_to="users/avatars/", **NULLABLE)
    country = CountryField(blank_label="(select country)", verbose_name="Страна", default="RU")
    about_message = models.TextField(verbose_name="О себе", **NULLABLE)
    is_blocked = models.BooleanField(verbose_name="Заблокирован", default=False)

    token = models.CharField(max_length=100, verbose_name='Token', **NULLABLE)

    # social messengers
    website = models.CharField(max_length=150, verbose_name="Сайт", default="https://", **NULLABLE)
    github = models.CharField(max_length=150, verbose_name="GitHub", default="", **NULLABLE)
    telegram = models.CharField(max_length=150, verbose_name="Telegram", default="@", **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

mailing_service/forms.py
from django import forms
from mailing_service.models import Mailing, Message, Client


class FormStyleMixin:
    """ Применение стилей к форме """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if (not isinstance(field.widget, forms.CheckboxInput) and
                    not isinstance(field.widget, forms.CheckboxSelectMultiple)):
                field.widget.attrs['class'] = 'form-control'


class MailingForm(FormStyleMixin, forms.ModelForm):
    """ Форма создания и редактирования рассылки """

    class Meta:
        model = Mailing
        fields = '__all__'
        exclude = ('is_active', 'status', 'is_published', 'user')

        widgets = {
            'first_send': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
            'finish_send': forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}),
            # 'client': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['client'].queryset = Client.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)

        clients = Client.objects.filter(user=user)

        if clients.exists():
            self.fields['client'].widget = forms.CheckboxSelectMultiple()
            self.fields['client'].queryset = clients
        else:
            self.fields['client'].widget = forms.TextInput(attrs={'value': 'Нет клиентов', 'readonly': True,
                                                                  'style': 'border: none; '
                                                                           'background-color: transparent;', })


class MessageForm(FormStyleMixin, forms.ModelForm):
    """ Форма создания и редактирования сообщения """

    class Meta:
        model = Message
        fields = '__all__'
        exclude = ('user',)


class ClientForm(FormStyleMixin, forms.ModelForm):
    """ Форма создания и редактирования сообщения """

    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('user',)

mailing_service/views.py
import json
from collections import Counter
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Permission
from django.utils import timezone

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from mailing_service.forms import MailingForm, MessageForm, ClientForm
from mailing_service.models import Client, Message, Mailing, MailingLogs
from mailing_service.services import MailingService, send_mailing, finish_task, delete_task
from mailing_service.templatetags.custom_filters import translate_month_from_num, translate_month

from users.models import User
from blogs.models import BlogPost
from users.services import is_moderator, is_user


@login_required(login_url='main:noway')
@user_passes_test(is_user, login_url='main:access_denied')
def dashboard(request):
    user = request.user
    mailing_list = Mailing.objects.filter(user=user)
    blogposts = BlogPost.objects.all().order_by('-view_count')[:3]
    formatted_posts = []

    for post in blogposts:
        published_date = post.created_at
        month = published_date.strftime('%B')
        day = published_date.strftime('%d')
        year = published_date.strftime('%Y')
        formatted_posts.append({
            'post': post,
            'publication_date': f"{translate_month(month)} {day}, {year}",
            'image': post.image,
        })

    today = timezone.now().date()
    now_month = timezone.now().month
    now_year = timezone.now().year

    month_mailing_count_list = [0] * 12
    last_week = [(today - timedelta(days=i - 1)).strftime('%d.%m') for i in range(7, 0, -1)]
    last_half_year = [translate_month_from_num((today - relativedelta(months=i - 1)).month) for i in range(6, 0, -1)]
    mailing_per_day = dict.fromkeys(last_week, 0)
    clients_added_half_year = dict.fromkeys(last_half_year, 0)

    for client in Client.objects.filter(user=user):
        month_client_added = translate_month_from_num(client.added_at.month)

        if client.added_at.year == now_year and month_client_added in last_half_year:
            clients_added_half_year[month_client_added] = clients_added_half_year.get(month_client_added, 0) + 1

    clients_added_half_year = list(clients_added_half_year.values())

    for mail in mailing_list:
        datetime_str = mail.first_send.strftime("%d/%m/%Y %H:%M:%S")
        date, time = datetime_str.split()
        month = int(date.split('/')[1][-1])
        mailing_year = int(date.split('/')[2])

        if mailing_year == now_year:
            for i in range(12):
                if i == month:
                    month_mailing_count_list[i - 1] += 1

        if mail.first_send.month == timezone.now().month:
            for i in range(7):
                day_ago = (today - timedelta(days=i)).strftime('%d.%m')

                if day_ago == mail.first_send.date().strftime('%d.%m'):
                    mailing_per_day[day_ago] = mailing_per_day.get(day_ago, 0) + 1

    mailing_per_day = list(mailing_per_day.values())
    now_month = translate_month_from_num(now_month)

    context = {
        'active_page': 'dashboard',
        'mailing_list': mailing_list,
        'client_list': [mail.client.all().filter(user=user) for mail in mailing_list],
        'mailing_per_day': mailing_per_day,
        'last_week': json.dumps(last_week, ensure_ascii=False),
        'month_mailing_count_list': month_mailing_count_list,
        'year': now_year,
        'now_month': json.dumps(now_month, ensure_ascii=False),
        'last_half_year': json.dumps(last_half_year, ensure_ascii=False),
        'clients_added_half_year': clients_added_half_year,
        'formatted_posts': formatted_posts,
    }
    # print(now_month)

    return render(request, 'mailing_service/dashboard.html', context)


@login_required(login_url='main:noway')
@user_passes_test(is_moderator, login_url='main:access_denied')
def moderator_dashboard(request):
    all_users = User.objects.all()
    # Подсчет встречаемости каждой страны среди пользователей
    countries = Counter(user.country.name for user in all_users if user.country)
    # Получаем общее количество упоминаний стран для нормализации данных
    total_count = sum(countries.values())
    # Сортировка и расчет процентного соотношения
    countries_sorted = sorted(countries.items(), key=lambda x: x[1], reverse=True)
    countries_percentage = [(name, int((count / total_count) * 100)) for name, count in countries_sorted]

    # Количество всех клиентов
    total_clients = 0

    for user in all_users:
        total_clients += len(user.client_set.all())

    # Количество всех рассылок
    total_mailings = 0

    for user in all_users:
        total_mailings += len(user.mailing_set.all())

    # Количество всех сообщений
    total_messages = 0

    for user in all_users:
        total_messages += len(user.message_set.all())

    # Количество всех пользователей
    total_users = 0

    for user in all_users:
        if not (user.is_superuser or user.is_staff):
            total_users += 1

    blogposts = BlogPost.objects.all().order_by('-view_count')[:3]
    total_blogs = len(BlogPost.objects.all())
    formatted_posts = []

    for post in blogposts:
        published_date = post.created_at
        month = published_date.strftime('%B')
        day = published_date.strftime('%d')
        year = published_date.strftime('%Y')
        formatted_posts.append({
            'post': post,
            'publication_date': f"{translate_month(month)} {day}, {year}",
            'image': post.image,
        })

    labels = ['Пользователи', 'Клиенты', 'Рассылки', 'Сообщения', 'Публикации']
    total_info = [total_users, total_clients, total_mailings, total_messages, total_blogs]
    zipped_data = zip(labels, total_info)

    context = {
        'title': "КАБИНЕТ МОДЕРАТОРА",
        'active_page': 'moderator_dashboard',
        'countries_percentage': countries_percentage[:3],
        'blogposts': blogposts,
        'formatted_posts': formatted_posts,
        'zipped_data': zipped_data,
    }
    print(formatted_posts[0]['post'].slug)

    return render(request, 'mailing_service/moderator_dashboard.html', context)


class ClientListView(LoginRequiredMixin, ListView):
    """ Просмотр списка клиентов """
    model = Client
    extra_context = {'title': 'КЛИЕНТЫ'}

    def get_context_data(self, **kwargs):
        """ Дополнительная информация """
        context = super().get_context_data(**kwargs)
        context['active_page'] = 'client_list'

        return context

    def get_queryset(self):
        """ Просмотр только своих климентов """
        user = self.request.user

        if user.is_superuser or user.is_staff:
            queryset = Client.objects.all()
        else:
            queryset = Client.objects.filter(user=user)

        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """ Валидация формы"""
        client = form.save(commit=False)
        client.user = self.request.user
        client.save()

        """ Если форма валидна, то отправляется сообщение"""

        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client'] = Client.objects.get(id=self.kwargs['pk'])

        return context


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """ Валидация формы"""
        client = form.save(commit=False)
        client.save()

        """ Если форма валидна, то отправляется сообщение"""

        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client'] = self.object

        return context


class MailingListView(LoginRequiredMixin, ListView):
    """ Просмотр списка клиентов """
    model = Mailing
    extra_context = {'title': 'РАССЫЛКИ'}
    permission_required = 'mailing_service.can_view_mailing'

    def get_queryset(self):
        """ Просмотр рассылок только своих клиентов """
        user = self.request.user

        if user.is_superuser or user.is_staff:
            queryset = Mailing.objects.all()
        else:
            queryset = Mailing.objects.filter(user=user, is_published=True)

        return queryset

    def get_context_data(self, **kwargs):
        """ Дополнительная информация """
        context = super().get_context_data(**kwargs)
        context['active_page'] = 'mailing_list'

        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    """ Создание новой рассылки """
    model = Mailing
    form_class = MailingForm
    extra_context = {'title': 'Создание рассылки'}
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['initial'] = {
            'first_send': datetime.now(),
            'finish_send': datetime.now() + timedelta(days=7),  # или любое другое значение по вашему выбору
        }

        return kwargs

    def form_valid(self, form):
        """ Валидация формы """
        mailing = form.save(commit=False)
        mailing.user = self.request.user

mailing_service/templates/mailing_service/includes/inc_inner_menu.html
{% load static %}
<style>
    .nav-link {
        color: inherit;
    }

    .nav-link.focus,
    .nav-link.active,
    .nav-link:hover {
        color: #c08081;
    }

    .nav-link {
        transition: color 0.3s, background-color 0.3s;
    }
</style>

<div class="sidebar border border-left col-md-3 col-lg-2 p-0">
    <div class="offcanvas-lg offcanvas-end" tabindex="-1" id="sidebarMenu"
         aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
            <ul class="nav flex-column">
                <li class="nav-item">
                    {% if user.is_staff %}
                    <a class="nav-link d-flex align-items-center gap-2 {% if active_page == 'moderator_dashboard' %}active{% endif %}"
                       data-toggle="tab" aria-current="page"
                       href="{% url 'mailing:moderator_dashboard' %}">
                        <svg class="bi">
                            <use xlink:href="#house-fill"/>
                        </svg>
                        Главная
                    </a>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 {% if active_page == 'user_list' %}active{% endif %}"
                       href="{% url 'users:user_list' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person-fill-gear" viewBox="0 0 16 16">
                            <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-9 8c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4m9.886-3.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382zM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0"/>
                        </svg>
                        Пользователи
                    </a>
                    {% else %}
                    <a class="nav-link d-flex align-items-center gap-2 {% if active_page == 'dashboard' %}active{% endif %}"
                       data-toggle="tab" aria-current="page"
                       href="{% url 'mailing:dashboard' %}">
                        <svg class="bi">
                            <use xlink:href="#house-fill"/>
                        </svg>
                        Главная
                    </a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 {% if active_page == 'mailing_list' %}active{% endif %}"
                       data-toggle="tab"
                       href="{% url 'mailing:mailing_list' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-envelope-at-fill" viewBox="0 0 16 16">
                            <path d="M2 2A2 2 0 0 0 .05 3.555L8 8.414l7.95-4.859A2 2 0 0 0 14 2zm-2 9.8V4.698l5.803 3.546zm6.761-2.97-6.57 4.026A2 2 0 0 0 2 14h6.256A4.5 4.5 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586zM16 9.671V4.697l-5.803 3.546.338.208A4.5 4.5 0 0 1 12.5 8c1.414 0 2.675.652 3.5 1.671"/>
                            <path d="M15.834 12.244c0 1.168-.577 2.025-1.587 2.025-.503 0-1.002-.228-1.12-.648h-.043c-.118.416-.543.643-1.015.643-.77 0-1.259-.542-1.259-1.434v-.529c0-.844.481-1.4 1.26-1.4.585 0 .87.333.953.63h.03v-.568h.905v2.19c0 .272.18.42.411.42.315 0 .639-.415.639-1.39v-.118c0-1.277-.95-2.326-2.484-2.326h-.04c-1.582 0-2.64 1.067-2.64 2.724v.157c0 1.867 1.237 2.654 2.57 2.654h.045c.507 0 .935-.07 1.18-.18v.731c-.219.1-.643.175-1.237.175h-.044C10.438 16 9 14.82 9 12.646v-.214C9 10.36 10.421 9 12.485 9h.035c2.12 0 3.314 1.43 3.314 3.034zm-4.04.21v.227c0 .586.227.8.581.8.31 0 .564-.17.564-.743v-.367c0-.516-.275-.708-.572-.708-.346 0-.573.245-.573.791"/>
                        </svg>
                        Рассылки
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 {% if active_page == 'message_list' %}active{% endif %}"
                       data-toggle="tab"
                       href="{% url 'mailing:message_list' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-chat-right-text-fill" viewBox="0 0 16 16">
                            <path d="M16 2a2 2 0 0 0-2-2H2a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h9.586a1 1 0 0 1 .707.293l2.853 2.853a.5.5 0 0 0 .854-.353zM3.5 3h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1m0 2.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1 0-1m0 2.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1"/>
                        </svg>
                        Письма
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 {% if active_page == 'client_list' %}active{% endif %}"
                       data-toggle="tab"
                       href="{% url 'mailing:client_list' %}">
                        <svg class="bi">
                            <use xlink:href="#people"/>
                        </svg>
                        Клиенты
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2 {% if active_page == 'log_list' %}active{% endif %}"
                       href="{% url 'mailing:log_list' %}">
                        <svg class="bi">
                            <use xlink:href="#graph-up"/>
                        </svg>
                        Отчеты
                    </a>
                </li>
            </ul>

            <hr class="my-3">

            <ul class="nav flex-column mb-auto">
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center gap-2" href="{% url 'users:profile' user.pk %}">
                        <svg class="bi">
                            <use xlink:href="#gear-wide-connected"/>
                        </svg>
                        Настройки
                    </a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="nav-link d-flex align-items-center gap-2" type="submit">
                            <svg class="bi">
                                <use xlink:href="#door-closed"/>
                            </svg>
                            Выйти
                        </button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>