config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls', 'main')),
    path("mailing/", include('mailing_service.urls', 'mailing')),
    path("users/", include('users.urls', 'users')),
    path("blogs/", include('blogs.urls', 'blogs')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_service/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_service.views import dashboard, ClientListView, MailingListView, MailingCreateView, MailingUpdateView, \
    MessageCreateView, MessageListView, ClientCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    MailingDetailView, MailingDeleteView, ClientDetailView, ClientUpdateView, ClientDeleteView, MailingLogListView, \
    toggle_mailing, moderator_dashboard
from mailing_service.apps import MailingServiceConfig


app_name = MailingServiceConfig.name


urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),  # кеширование убрала потому что можно снова попасть в ЛК
    path('moderator_dashboard/', moderator_dashboard, name='moderator_dashboard'),

    path('client_list/', cache_page(5)(ClientListView.as_view()), name='client_list'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('view_client/<int:pk>', ClientDetailView.as_view(), name='view_client'),
    path('update_client/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),

    path('mailing_list/', cache_page(5)(MailingListView.as_view()), name='mailing_list'),
    path('create_mail/', MailingCreateView.as_view(), name='create_mail'),
    path('view_mail/<int:pk>', MailingDetailView.as_view(), name='view_mail'),
    path('update_mail/<int:pk>/', MailingUpdateView.as_view(), name='update_mail'),
    path('delete_mail/<int:pk>/', MailingDeleteView.as_view(), name='delete_mail'),

    path('message_list/', cache_page(5)(MessageListView.as_view()), name='message_list'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('view_message/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),

    path('log_list/', cache_page(5)(MailingLogListView.as_view()), name='log_list'),
    path('toggle_mailing/<int:pk>', toggle_mailing, name='toggle_mailing'),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import index, contacts, noway_page, access_denied

app_name = MainConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('noway/', noway_page, name='noway'),
    path('access_denied/', access_denied, name='access_denied'),
]

mailing_service/models.py
from django.db import models

from config import settings
from users.models import User

NULLABLE = {'null': True, 'blank': True}


# Create your models here.
class Client(models.Model):
    """ Клиент """
    objects = models.Manager()

    name = models.CharField(max_length=150, verbose_name='Фамилия Имя Отчество')
    email = models.EmailField(unique=False, verbose_name='Email')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Действующий')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    added_at = models.DateField(auto_now_add=True, verbose_name="Дата добавления")

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('name',)

    def __str__(self):
        return f'{self.name} [{self.email}]'


class Message(models.Model):
    """ Сообщение для рассылки """
    objects = models.Manager()

    message_subject = models.CharField(max_length=150, verbose_name='Тема письма')
    message_body = models.TextField(verbose_name='Тело письма')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('message_subject',)

    def __str__(self):
        return f'{self.message_subject}'


class Mailing(models.Model):
    """ Рассылка """

    PERIODICITY_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    )

    objects = models.Manager()

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')
    first_send = models.DateTimeField(verbose_name='Дата и время отправки')
    finish_send = models.DateTimeField(verbose_name='Дата и время завершения рассылки')
    periodicity = models.CharField(max_length=20, choices=PERIODICITY_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, verbose_name='Статус рассылки')

    client = models.ManyToManyField(Client, verbose_name='Клиент', related_name='mailings')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('-first_send',)

    def __str__(self):
        return f'Рассылка: {self.pk}'

    def deactivate_post(self):
        """ Деактивация пост рассылки """
        self.is_published = False
        self.status = 'completed'
        self.save()


class MailingLogs(models.Model):
    """ Логи рассылки """
    STATUS = [
        ('success', 'Успешно'),
        ('failed', 'Неудачно'),
    ]

    objects = models.Manager()

    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус отправки')
    server_response = models.TextField(verbose_name='Ответ сервера', **NULLABLE)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка', **NULLABLE)

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылок'
        ordering = ('-date_time',)

    def __str__(self):
        return f'Лог рассылки: {self.pk}'

mailing_service/views.py
import json
from collections import Counter
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Permission
from django.utils import timezone

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from mailing_service.forms import MailingForm, MessageForm, ClientForm
from mailing_service.models import Client, Message, Mailing, MailingLogs
from mailing_service.services import MailingService, send_mailing, finish_task, delete_task
from mailing_service.templatetags.custom_filters import translate_month_from_num, translate_month

from users.models import User
from blogs.models import BlogPost
from users.services import is_moderator, is_user


@login_required(login_url='main:noway')
@user_passes_test(is_user, login_url='main:access_denied')
def dashboard(request):
    user = request.user
    mailing_list = Mailing.objects.filter(user=user)
    blogposts = BlogPost.objects.all().order_by('-view_count')[:3]
    formatted_posts = []

    for post in blogposts:
        published_date = post.created_at
        month = published_date.strftime('%B')
        day = published_date.strftime('%d')
        year = published_date.strftime('%Y')
        formatted_posts.append({
            'post': post,
            'publication_date': f"{translate_month(month)} {day}, {year}",
            'image': post.image,
        })

    today = timezone.now().date()
    now_month = timezone.now().month
    now_year = timezone.now().year

    month_mailing_count_list = [0] * 12
    last_week = [(today - timedelta(days=i - 1)).strftime('%d.%m') for i in range(7, 0, -1)]
    last_half_year = [translate_month_from_num((today - relativedelta(months=i - 1)).month) for i in range(6, 0, -1)]
    mailing_per_day = dict.fromkeys(last_week, 0)
    clients_added_half_year = dict.fromkeys(last_half_year, 0)

    for client in Client.objects.filter(user=user):
        month_client_added = translate_month_from_num(client.added_at.month)

        if client.added_at.year == now_year and month_client_added in last_half_year:
            clients_added_half_year[month_client_added] = clients_added_half_year.get(month_client_added, 0) + 1

    clients_added_half_year = list(clients_added_half_year.values())

    for mail in mailing_list:
        datetime_str = mail.first_send.strftime("%d/%m/%Y %H:%M:%S")
        date, time = datetime_str.split()
        month = int(date.split('/')[1][-1])
        mailing_year = int(date.split('/')[2])

        if mailing_year == now_year:
            for i in range(12):
                if i == month:
                    month_mailing_count_list[i - 1] += 1

        if mail.first_send.month == timezone.now().month:
            for i in range(7):
                day_ago = (today - timedelta(days=i)).strftime('%d.%m')

                if day_ago == mail.first_send.date().strftime('%d.%m'):
                    mailing_per_day[day_ago] = mailing_per_day.get(day_ago, 0) + 1

    mailing_per_day = list(mailing_per_day.values())
    now_month = translate_month_from_num(now_month)

    context = {
        'active_page': 'dashboard',
        'mailing_list': mailing_list,
        'client_list': [mail.client.all().filter(user=user) for mail in mailing_list],
        'mailing_per_day': mailing_per_day,
        'last_week': json.dumps(last_week, ensure_ascii=False),
        'month_mailing_count_list': month_mailing_count_list,
        'year': now_year,
        'now_month': json.dumps(now_month, ensure_ascii=False),
        'last_half_year': json.dumps(last_half_year, ensure_ascii=False),
        'clients_added_half_year': clients_added_half_year,
        'formatted_posts': formatted_posts,
    }
    # print(now_month)

    return render(request, 'mailing_service/dashboard.html', context)


@login_required(login_url='main:noway')
@user_passes_test(is_moderator, login_url='main:access_denied')
def moderator_dashboard(request):
    all_users = User.objects.all()
    # Подсчет встречаемости каждой страны среди пользователей
    countries = Counter(user.country.name for user in all_users if user.country)
    # Получаем общее количество упоминаний стран для нормализации данных
    total_count = sum(countries.values())
    # Сортировка и расчет процентного соотношения
    countries_sorted = sorted(countries.items(), key=lambda x: x[1], reverse=True)
    countries_percentage = [(name, int((count / total_count) * 100)) for name, count in countries_sorted]

    # Количество всех клиентов
    total_clients = 0

    for user in all_users:
        total_clients += len(user.client_set.all())

    # Количество всех рассылок
    total_mailings = 0

    for user in all_users:
        total_mailings += len(user.mailing_set.all())

    # Количество всех сообщений
    total_messages = 0

    for user in all_users:
        total_messages += len(user.message_set.all())

    # Количество всех пользователей
    total_users = 0

    for user in all_users:
        if not (user.is_superuser or user.is_staff):
            total_users += 1

    blogposts = BlogPost.objects.all().order_by('-view_count')[:3]
    total_blogs = len(BlogPost.objects.all())
    formatted_posts = []

    for post in blogposts:
        published_date = post.created_at
        month = published_date.strftime('%B')
        day = published_date.strftime('%d')
        year = published_date.strftime('%Y')
        formatted_posts.append({
            'post': post,
            'publication_date': f"{translate_month(month)} {day}, {year}",
            'image': post.image,
        })

    labels = ['Пользователи', 'Клиенты', 'Рассылки', 'Сообщения', 'Публикации']
    total_info = [total_users, total_clients, total_mailings, total_messages, total_blogs]
    zipped_data = zip(labels, total_info)

    context = {
        'title': "КАБИНЕТ МОДЕРАТОРА",
        'active_page': 'moderator_dashboard',
        'countries_percentage': countries_percentage[:3],
        'blogposts': blogposts,
        'formatted_posts': formatted_posts,
        'zipped_data': zipped_data,
    }
    print(formatted_posts[0]['post'].slug)

    return render(request, 'mailing_service/moderator_dashboard.html', context)


class ClientListView(LoginRequiredMixin, ListView):
    """ Просмотр списка клиентов """
    model = Client
    extra_context = {'title': 'КЛИЕНТЫ'}

    def get_context_data(self, **kwargs):
        """ Дополнительная информация """
        context = super().get_context_data(**kwargs)
        context['active_page'] = 'client_list'

        return context

    def get_queryset(self):
        """ Просмотр только своих климентов """
        user = self.request.user

        if user.is_superuser or user.is_staff:
            queryset = Client.objects.all()
        else:
            queryset = Client.objects.filter(user=user)

        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """ Валидация формы"""
        client = form.save(commit=False)
        client.user = self.request.user
        client.save()

        """ Если форма валидна, то отправляется сообщение"""

        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client'] = Client.objects.get(id=self.kwargs['pk'])

        return context


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        """ Валидация формы"""
        client = form.save(commit=False)
        client.save()

        """ Если форма валидна, то отправляется сообщение"""

        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client'] = self.object

        return context


class MailingListView(LoginRequiredMixin, ListView):
    """ Просмотр списка клиентов """
    model = Mailing
    extra_context = {'title': 'РАССЫЛКИ'}
    permission_required = 'mailing_service.can_view_mailing'

    def get_queryset(self):
        """ Просмотр рассылок только своих клиентов """
        user = self.request.user

        if user.is_superuser or user.is_staff:
            queryset = Mailing.objects.all()
        else:
            queryset = Mailing.objects.filter(user=user, is_published=True)

        return queryset

    def get_context_data(self, **kwargs):
        """ Дополнительная информация """
        context = super().get_context_data(**kwargs)
        context['active_page'] = 'mailing_list'

        return context


class MailingCreateView(LoginRequiredMixin, CreateView):
    """ Создание новой рассылки """
    model = Mailing
    form_class = MailingForm
    extra_context = {'title': 'Создание рассылки'}
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['initial'] = {
            'first_send': datetime.now(),
            'finish_send': datetime.now() + timedelta(days=7),  # или любое другое значение по вашему выбору
        }

        return kwargs

    def form_valid(self, form):
        """ Валидация формы """
        mailing = form.save(commit=False)
        mailing.user = self.request.user

mailing_service/templates/mailing_service/client_confirm_delete.html
<!doctype html>
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<Style>
    /* Общие стили для контейнера */
    .container-form {
        display: flex;
    }

    .card {
        width: 100%;            /* Ширина карточки на всю доступную ширину */
        max-width: 600px;       /* Максимальная ширина карточки */
        padding: 20px;          /* Отступы внутри карточки */
        box-shadow: 0 4px 8px rgb(79 71 71); /* Тень для карточки */
        background: dark;      /* Фон карточки белый */
        border-radius: 8px;     /* Скругление углов карточки */
    }

    .box {
        text-align: center;
        height: 200px;
        margin-top: 20px;
    }

    /* Настройка заголовка формы */
    h3 {
        text-align: center; /* Центрирование заголовка */
        margin-bottom: 20px; /* Отступ снизу для заголовка */
    }

    p {
        font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
        font-size: 24px;
        font-weight: 200;

    }
</Style>

<div class="container-form justify-content-center align-items-center text-center">
    <form class="mb-5" method="post" id="contactForm">
        <h3>Удаление клиента</h3>
        <div class="card border-0">
            <div class="box">
                {% csrf_token %}
                <p><strong>Вы действительно хотите удалить:</strong><br><br>{{ client.name }}</p>
            </div>

            <button class="btn btn-danger sm_btn mt-1 mb-2" type="submit">Да, удалить</button>
            <span class="submitting"></span>
            <a href="{% url 'mailing:client_list' %}" class="btn btn-warning sm_btn">Нет, вернуться назад</a>

        </div>
    </form>
</div>


{% endblock %}

mailing_service/templates/mailing_service/client_detail.html
<!doctype html>
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<Style>
    /* Общие стили для контейнера */
        .container-form {
            display: flex;
        }

        .card {
            width: 100%;            /* Ширина карточки на всю доступную ширину */
            max-width: 600px;       /* Максимальная ширина карточки */
            padding: 20px;          /* Отступы внутри карточки */
            box-shadow: 0 4px 8px rgb(79 71 71); /* Тень для карточки */
            background: dark;      /* Фон карточки белый */
            border-radius: 8px;     /* Скругление углов карточки */
        }

        /* Настройка заголовка формы */
        h3 {
            text-align: center; /* Центрирование заголовка */
            margin-bottom: 20px; /* Отступ снизу для заголовка */
        }
</Style>

<div class="container-form justify-content-center align-items-center text-center">
    <form class="mb-5" method="post" id="contactForm" name="contactForm">
        <h3>Информация о клиенте</h3>
        <div class="card border-0">
            <div class="box">
                <strong>Фамилия Имя Отчество:</strong><br> {{ client.name }}<br><hr>
                <strong>Email:</strong><br> {{ client.email }} <br><hr>
                {% if client.is_active %}
                <strong>Действующий:</strong> Да <br><hr>
                {% else %}
                <strong>Действующий:</strong><br>Нет <br><hr>
                {% endif %}
                <strong>Комментарий:</strong><br>{{ client.comment }} <br>
                {% if user.is_staff or user.is_superuser %}
                <br><hr>
                <strong>Пользователь:</strong><br>{{ client.user }} <br>
                {% endif %}
            </div>

            <span class="submitting"></span> <br>
            <a href="{% url 'mailing:client_list' %}" class="btn btn-warning sm_btn">Назад</a>
        </div>
    </form>
</div>


{% endblock %}

mailing_service/templates/mailing_service/client_form.html
<!doctype html>
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<Style>
    /* Общие стили для контейнера */
        .container-form {
            display: flex;
        }

        .card {
            width: 100%;            /* Ширина карточки на всю доступную ширину */
            max-width: 600px;       /* Максимальная ширина карточки */
            padding: 20px;          /* Отступы внутри карточки */
            box-shadow: 0 4px 8px rgba(0,0,0,0.1); /* Тень для карточки */
            background: dark;      /* Фон карточки белый */
            border-radius: 8px;     /* Скругление углов карточки */
        }

        /* Настройка заголовка формы */
        h3 {
            text-align: center; /* Центрирование заголовка */
            margin-bottom: 20px; /* Отступ снизу для заголовка */
        }
</Style>

<div class="container-form justify-content-center align-items-center text-center">
    <form class="mb-5" method="post" id="contactForm" name="contactForm">
        <h3>Добавление клиента</h3>
        <div class="card border-0">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>

            <button type="submit" value="Добавить"
                    class="btn btn-success rounded-2 sm_btn mt-1 mb-2">Сохранить
            </button>
            <span class="submitting"></span>
            <a href="{% url 'mailing:client_list' %}" class="btn btn-warning sm_btn">Назад</a>
        </div>
    </form>
</div>


{% endblock %}

mailing_service/templates/mailing_service/custom-input.html
<!-- templates/bootstrap_datepicker_plus/input.html -->
<!-- Datepicker -->
<!-- jQuery (если еще не подключен) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Moment.js (необходим для bootstrap-datetimepicker) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

<!-- Bootstrap (если используете) -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- Bootstrap Datepicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">

<div class="input-group dbdp">
    <input type='text' id="id_first_send" name="first_send" class="form-control datetimepicker"/>
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
    </span>
</div>

<div class="input-group dbdp">
    <input type='text' id="id_finish_send" name="finish_send" class="form-control datetimepicker"/>
    <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
    </span>
</div>

<script>
    $(function () {
        $('.datetimepicker').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss'
        });

        // Обработка изменений для каждого поля
        $('#id_first_send').on('dp.change', function(e) {
            $(this).val(e.date.format('YYYY-MM-DD HH:mm:ss'));
        });

        $('#id_finish_send').on('dp.change', function(e) {
            $(this).val(e.date.format('YYYY-MM-DD HH:mm:ss'));
        });
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

mailing_service/templates/mailing_service/mailing_confirm_delete.html
<!doctype html>
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

<Style>
    /* Общие стили для контейнера */
    .container-form {
        display: flex;
    }

    .card {
        width: 100%;            /* Ширина карточки на всю доступную ширину */
        max-width: 600px;       /* Максимальная ширина карточки */
        padding: 20px;          /* Отступы внутри карточки */
        box-shadow: 0 4px 8px rgb(79 71 71); /* Тень для карточки */
        background: dark;      /* Фон карточки белый */
        border-radius: 8px;     /* Скругление углов карточки */

    }

    .box {
        text-align: left;
        height: 100%;
    }

    /* Настройка заголовка формы */
    h3 {
        text-align: center; /* Центрирование заголовка */
        margin-bottom: 20px; /* Отступ снизу для заголовка */
    }

    .confirm_text {
        font-size: 24px;
        font-weight: bold;
        text-align: center;
    }
</Style>

<div class="container-form justify-content-center align-items-center text-center">
    <form class="mb-5" method="post" id="contactForm">
        <h3>Удаление рассылки</h3>
        <div class="card border-0">
            <div class="box">
                {% csrf_token %}
                <p class="confirm_text">Вы действительно хотите удалить рассылку?</p><br>
                <strong>Тема:</strong><br> {{ mail.message.message_subject }}<br><hr>
                <strong>Сообщение:</strong><br>  {{ mail.message.message_body }} <br><br><hr>
                <strong>Создано:</strong> {{ mail.first_send }} <br><hr>
                <strong>Периодичность:</strong> {{ mail.periodicity }} <br><hr>
                <strong>Статус:</strong>  {{ mail.status }} <br><hr><br>
            </div>

            <button class="btn btn-danger sm_btn mt-1 mb-2" type="submit">Да, удалить</button>
            <span class="submitting"></span>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning sm_btn">Нет, вернуться назад</a>

        </div>
    </form>
</div>


{% endblock %}

mailing_service/templates/mailing_service/mailing_detail.html
<!doctype html>
{% extends 'main/base.html' %}
{% load custom_filters %}
{% load static %}
{% block content %}

<Style>
    /* Общие стили для контейнера */
    .container-form {
        display: flex;
    }

    .card {
        width: 100%;            /* Ширина карточки на всю доступную ширину */
        max-width: 600px;       /* Максимальная ширина карточки */
        padding: 20px;          /* Отступы внутри карточки */
        box-shadow: 0 4px 8px rgb(79 71 71); /* Тень для карточки */
        background: dark;      /* Фон карточки белый */
        border-radius: 8px;     /* Скругление углов карточки */
    }

    /* Настройка заголовка формы */
    h3 {
        text-align: center; /* Центрирование заголовка */
        margin-bottom: 20px; /* Отступ снизу для заголовка */
    }

</Style>

<div class="container-form justify-content-center align-items-center text-center">
    <div>
        <h3>Детали рассылки</h3>
        <div class="card border-0">
            <div class="box">
                <strong>Тема:</strong><br> {{ mail.message.message_subject }}<br>
                <hr>
                <strong>Сообщение:</strong><br> {{ mail.message.message_body }} <br><br>
                <hr>
                <strong>Создано:</strong> {{ mail.created_at }} <br>
                <strong>Старт рассылки:</strong> {{ mail.first_send }} <br>
                <strong>Окончание рассылки:</strong> {{ mail.finish_send }} <br>
                <hr>
                <strong>Периодичность:</strong> {{ mail.periodicity|translate_periodicity }} <br>
                <strong>Статус:</strong> {{ mail.status|translate_status }} <br>
                <hr>

                <strong>Клиенты:</strong>
                <ul>
                    {% for client in clients %}
                    <li>{{ client }}</li>
                    {% endfor %}
                </ul>
                <br>
            </div>

            {% if user.is_staff or user.is_superuser %}
            {% if mailing.status == 'created' or mailing.status == 'started' %}
            <form method="post" action="{% url 'mailing:toggle_mailing' mailing.id %}">
                {% csrf_token %}
                <!--                                <input type="hidden" name="mailing_id" value="{{ mailing.id }}">-->
                <button id="block-button-{{ mailing.id }}"
                        class="btn sm_btn btn-outline-{% if mailing.is_published %}danger{% else %}success{% endif %} text_button">
                    {% if mailing.is_published %}Отключить{% else %}Включить{% endif %}
                </button>
            </form>
            {% endif %}
            {% endif %}

            <span class="submitting"></span> <br>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning sm_btn">Назад</a>
        </div>
    </div>
</div>


{% endblock %}